<!DOCTYPE html>
<html>

<head>
    <title>promise</title>
    <script>
        function countdown(seconds){
            return new Promise(function(resolve,reject){
                for(let i=seconds;i>0;i--){
                    setTimeout(function(){
                        //测试：当数到13时返回一个错误
                        if(i===13) return reject(new Error("definitely not counting that"));
                        if(i>0) console.log(i+'...');
                        else resolve(console.log("go!"));
                    },(seconds-1)*1000);
                }
            })
        }

        countdown(5).then({
            function () {
                console.log("countdown complete successfully");
            },
            function (err) {
                console.log("countdown experienced an error:"+err.message);
            }
        })

        const p = countdown(15);
        p.then(function () {
                console.log("countdown complete successfully");
            });
        p.catch(function (err) {
                console.log("countdown experienced an error:"+err.message);
            });
        
    </script>
</head>

<body>
   
</body>

</html>
